### ISSUE TITLE
BUG：-s参数问题

### ISSUE THREAD

**Issue by f1owkang** [a76yyyy/HustWebAuth#1]
在认证界面是’中国电信(telecom)‘
`servicetype: '%25E4%25B8%25AD%25E5%259B%25BD%25E7%2594%25B5%25E4%25BF%25A1(telecom)`
配置如上参数，可以进行认证，也可以上网了，但是报错
```
2023/04/28 08:11:59 Using config file: /root/HustWebAuth.yaml
panic: runtime error: index out of range [3] with length 1
goroutine 1 [running]:
github.com/a76yyyy/HustWebAuth/cmd.Login()
        /home/runner/work/HustWebAuth/HustWebAuth/cmd/login.go:136 +0x410
github.com/a76yyyy/HustWebAuth/cmd.glob..func2(0x899940, {0x2c0cac8, 0x0, 0x1})
        /home/runner/work/HustWebAuth/HustWebAuth/cmd/login.go:25 +0x34
github.com/spf13/cobra.(*Command).execute(0x899940, {0x2c0cab8, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x838
github.com/spf13/cobra.(*Command).ExecuteC(0x899ac0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x4b8
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/a76yyyy/HustWebAuth/cmd.Execute()
        /home/runner/work/HustWebAuth/HustWebAuth/cmd/root.go:179 +0x40
main.main()
        /home/runner/work/HustWebAuth/HustWebAuth/main.go:29 +0x34
```

**Comment by f1owkang** [comment]
测试没问题啦，谢谢
